import {recommend,normalizeNeeds,confirmedConfiguration,tasks,languages,preferences,runInstructions} from './recommendations.js';
import {configurations} from './device-data.js';
import {readPreference,writePreference} from './browser-storage.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const gb=n=>n==null?'Not assessed':(Number(n)/1024**3).toLocaleString('en',{maximumFractionDigits:1})+' GB';
const label=c=>`${c.chip.name} · ${c.chip.memory_kind==='discrete'?c.vram_gib:c.ram_gib} GB`;
const options=(obj,v)=>Object.entries(obj).map(([k,text])=>`<option value="${k}" ${k===v?'selected':''}>${text}</option>`).join('');
const progress=step=>`<ol class="find-progress" aria-label="Recommendation steps">${['Your computer','Your work','Your models'].map((s,i)=>`<li class="${i===step?'active':i<step?'done':''}"${i===step?' aria-current="step"':''}><span aria-hidden="true">${i<step?'✓':String(i+1).padStart(2,'0')}</span>${s}</li>`).join('')}</ol>`;
export function mountFind(root,{catalog,hardware,fetchCompatibility,onConfirm,onForget}){
 const configs=configurations(hardware);let config=confirmedConfiguration(readPreference('macfit.recommendation.profile',null),configs),needs=normalizeNeeds(readPreference('macfit.recommendation.needs',{})),ready=readPreference('macfit.recommendation.needs-confirmed',false)===true;
 let stage=!config||new URLSearchParams(location.search).get('edit')==='device'?'device':ready?'results':'needs',state='idle',error='',result=null,controller=null,alive=true,sessionOnly=false;
 const save=(k,v)=>{if(!writePreference(k,v))sessionOnly=true;};
 function heading(title,subtitle){return `<div class="find-heading"><h1 tabindex="-1" data-find-heading>${title}</h1><p>${subtitle}</p></div>`;}
 function render({focus=false}={}){const oldHeading=root.querySelector('[data-find-heading]'),keepHeadingFocus=oldHeading!=null&&document.activeElement===oldHeading;renderContent();if(focus||keepHeadingFocus)root.querySelector('[data-find-heading]')?.focus({preventScroll:true});}
 function renderContent(){root.innerHTML=progress(stage==='device'?0:stage==='needs'?1:2)+(error?`<p class="mine-notice" role="alert">${esc(error)}</p>`:'')+(sessionOnly?'<p class="mine-notice" role="status">Your settings work for this session. Browser storage is unavailable, so refreshing or closing this page may clear them.</p>':'');
 if(stage==='device'){root.innerHTML+=heading('A good fit starts with your computer.','Tell us what you use. We’ll find a model that fits your memory budget.')+`<section class="card find-device"><div class="find-device-art"><svg viewBox="0 0 200 145" fill="none" aria-hidden="true"><rect x="28" y="12" width="144" height="99" rx="9"/><path d="M15 119h170l-11 13H27z"/><path d="m77 60 15 15 33-33"/></svg><span>Built around your hardware</span></div><form id="find-device-form"><label for="find-device">Your computer configuration</label><select id="find-device" required><option value="">Choose your chip and memory</option>${['unified','discrete','system'].map(kind=>`<optgroup label="${{unified:'Mac · Apple Silicon',discrete:'PC · Dedicated GPU',system:'PC · CPU'}[kind]}">${configs.filter(c=>c.chip.memory_kind===kind).map(c=>`<option value="${esc(c.id)}" ${config?.id===c.id?'selected':''}>${esc(label(c))}</option>`).join('')}</optgroup>`).join('')}</select><p class="mine-small">Mac: Apple menu → About This Mac. Windows: Task Manager → Performance.</p><label class="confirmation-check"><input id="find-confirm" type="checkbox" required> I checked my chip and memory.</label><button class="button primary full" type="submit">Continue to my needs →</button></form></section>`;return;}
 const deviceBar=`<div class="find-device-bar"><span class="mine-status-dot"></span><strong>${esc(label(config))}</strong><button data-find="device">Change computer</button></div>`;
 if(stage==='needs'){root.innerHTML+=heading('What would you like to do?','A little about your work helps us narrow things down.')+`<section class="card find-needs">${deviceBar}<form id="find-needs-form"><fieldset><legend>My main use</legend><div class="find-task-grid">${Object.entries(tasks).map(([id,title],i)=>`<label><input type="radio" name="task" value="${id}" ${needs.task===id?'checked':''}><span class="find-task-symbol">${['✦','⌘','Aa','▤'][i]}</span><strong>${title}</strong><span>${{general:'Questions, ideas and everyday help',coding:'Write, debug and understand code',writing:'Draft, rewrite and find the right words',documents:'Work through documents and sources'}[id]}</span></label>`).join('')}</div></fieldset><div class="find-preferences"><label>Main language<select name="language">${options(languages,needs.language)}</select></label><label>What matters most<select name="preference">${options(preferences,needs.preference)}</select></label></div><details class="mine-advanced"><summary>Advanced settings</summary><label>Context window<select name="context">${[4096,8192,16384].map(n=>`<option value="${n}" ${needs.context===n?'selected':''}>${n/1024}K tokens</option>`).join('')}</select></label><p>Longer context uses more memory. The budget includes both your input and the model’s answer.</p></details><button class="button primary full" type="submit">Find my models →</button></form></section>`;return;}
 root.innerHTML+=heading('Your computer. Your shortlist.','Choose a starting point, then make it work your way.')+`<div class="find-results-bar">${deviceBar}<span>${esc(tasks[needs.task])} · ${esc(languages[needs.language])}</span><button class="inline-link" data-find="needs">Edit my needs</button></div>`;
 if(state==='loading'){root.innerHTML+='<div class="card find-loading" role="status"><span class="loading-indicator"></span><h2>Finding your fit…</h2><p>Checking model files, memory and runtime support.</p></div>';return;}
 if(state==='error'){root.innerHTML+='<div class="card mine-empty"><h2>We couldn’t load your choices.</h2><button class="button primary" data-find="retry">Try again</button></div>';return;}
 if(!result)return;
 const seen=new Set(),cards=[...result.ranked,...result.pending.filter(c=>c.fitting)].filter(c=>{if(seen.has(c.model.id)||!runInstructions(c.artifact,config,needs.context))return false;seen.add(c.model.id);return true;}).slice(0,3);
 if(!cards.length){root.innerHTML+='<section class="card mine-empty"><h2>Let’s find another starting point.</h2><p>No recorded version fits all of this device’s current checks. Try a shorter context or explore the model library.</p><div class="mine-actions"><button class="button primary" data-find="needs">Adjust my needs</button><a class="button secondary" href="/models">Explore models</a></div></section>';return;}
 root.innerHTML+=`<div class="find-card-grid">${cards.map((c,i)=>{const suffix=`?artifact=${encodeURIComponent(c.artifact.id)}&context=${needs.context}`;return `<article class="card find-model-card"><div class="find-card-top"><span class="find-option">OPTION 0${i+1}</span><span class="mine-icon">${esc(c.model.name.slice(0,1))}</span></div><h2><a href="/model/${esc(c.model.id)}">${esc(c.model.name)}</a></h2><p class="find-model-role">${c.task?`${esc(tasks[needs.task])} · documented capability`:'A local starting point to try'}</p><span class="mine-status">Within your memory budget</span><dl class="find-model-stats"><div><dt>Model size</dt><dd>${gb(c.artifact.actual_size_bytes)}</dd></div><div><dt>Memory plan</dt><dd>${gb(c.row.estimated_required_bytes)}</dd></div><div><dt>Speed</dt><dd>${c.measured?Number(c.measured.generation_tokens_per_second).toFixed(1)+' tok/s':'Try it locally'}</dd></div></dl><a class="button primary full" href="/run/${esc(c.artifact.id)}?device=${esc(config.id)}&context=${needs.context}">Run on my computer ↗</a><div class="find-next-actions"><a href="/optimize/${esc(c.model.id)}${suffix}">Optimize for my computer <span>→</span></a><a href="/customize/${esc(c.model.id)}${suffix}">Make it mine <span>✦</span></a></div><details class="mine-advanced"><summary>Why this option? · Advanced</summary><p>${esc(c.task?.reason||'Task performance needs a local trial.')}</p><p>${esc(c.language?.reason||'Language quality needs a local trial.')}</p><p>Version: ${esc(c.artifact.quantization)} · ${esc(c.artifact.runtime_family)}. Context: ${needs.context/1024}K.</p><p>Memory is estimated. The exact runtime and response quality still need testing on your computer.</p>${c.task?.source_url?.startsWith('https://')?`<a href="${esc(c.task.source_url)}" target="_blank" rel="noopener noreferrer">Publisher information ↗</a>`:''}</details></article>`;}).join('')}</div><div class="find-after"><span>Start simple. Make it yours when you’re ready.</span><a href="/models">Explore all models →</a></div>`;
 }
 async function load({focus=true}={}){controller?.abort();controller=new AbortController();const request=controller;state='loading';error='';render({focus});try{const data=await fetchCompatibility(config.id,needs.context,{artifactsOnly:true,signal:request.signal});if(!alive||request.signal.aborted)return;result=recommend({models:catalog.models,artifacts:catalog.artifacts,assessments:data.items,config,needs,benchmarks:catalog.benchmarks,evaluations:catalog.quality_evaluations});state='ready';render({focus});}catch(e){if(!alive||request.signal.aborted)return;state='error';error=e.message||'Please try again.';render({focus});}}
 const onSubmit=e=>{e.preventDefault();error='';try{if(e.target.id==='find-device-form'){config=configs.find(c=>c.id===root.querySelector('#find-device').value);if(!config||!root.querySelector('#find-confirm').checked)return;save('macfit.recommendation.profile',{confirmed:true,deviceId:config.id,confirmedAt:new Date().toISOString()});onConfirm?.(config);stage='needs';history.replaceState({},'','/for-your-device');render({focus:true});}else if(e.target.id==='find-needs-form'){needs=normalizeNeeds(Object.fromEntries(new FormData(e.target)));save('macfit.recommendation.needs',needs);save('macfit.recommendation.needs-confirmed',true);stage='results';load();}window.scrollTo(0,0);}catch(e){error='We couldn’t update your choices. Please try again.';render({focus:true});}};
 const onClick=e=>{const b=e.target.closest('[data-find]');if(!b)return;controller?.abort();error='';if(b.dataset.find==='device')stage='device';if(b.dataset.find==='needs')stage='needs';if(b.dataset.find==='retry'){load();return;}render({focus:true});};
 root.addEventListener('submit',onSubmit);root.addEventListener('click',onClick);
 render();if(stage==='results')load({focus:false});return ()=>{alive=false;controller?.abort();root.removeEventListener('submit',onSubmit);root.removeEventListener('click',onClick);};
}
