import {configurations} from './device-data.js';
import {confirmedConfiguration,runInstructions} from './recommendations.js';
import {fittingOptions,runtimeSpec} from './personal-domain.js';
import {runner} from './runtime-template.js';
import {readPreference} from './browser-storage.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const gb=n=>(Number(n)/1024**3).toLocaleString('en',{maximumFractionDigits:1})+' GB';
export function mountLocalRun(root,{catalog,hardware,fetchCompatibility}){
 let alive=true,selected=null;const controller=new AbortController(),params=new URLSearchParams(location.search),proof=readPreference('macfit.recommendation.profile',null);
 const config=confirmedConfiguration(proof,configurations(hardware)),context=Number(params.get('context')||8192);
 let artifactId='';try{artifactId=decodeURIComponent(location.pathname.split('/')[2]||'');}catch{}
 const artifact=/^[A-Za-z0-9][A-Za-z0-9_.-]{0,127}$/.test(artifactId)?catalog.artifacts.find(a=>a.id===artifactId):null,model=catalog.models.find(m=>m.id===artifact?.model_id);
 function show(html){const hadFocus=root.contains(document.activeElement);root.innerHTML=html;if(hadFocus)root.querySelector('[data-run-heading]')?.focus({preventScroll:true});}
 if(!model||![4096,8192,16384].includes(context)){show('<section class="card mine-empty"><h1 tabindex="-1" data-run-heading>This version is unavailable.</h1><p>The link may be incomplete or out of date.</p><a class="button primary" href="/for-your-device">Find another model</a></section>');return ()=>{};}
 if(!config||config.id!==params.get('device')){show('<section class="card mine-empty"><h1 tabindex="-1" data-run-heading>Confirm your computer first.</h1><p>We’ll check the right version for your hardware.</p><a class="button primary" href="/for-your-device?edit=device">Confirm my computer</a></section>');return ()=>{};}
 show('<section class="card find-loading" role="status"><h1 tabindex="-1" data-run-heading>Preparing your run guide…</h1></section>');
 (async()=>{try{const data=await fetchCompatibility(config.id,context,{modelId:model.id,signal:controller.signal});if(!alive)return;selected=fittingOptions(catalog,data.items,config,{context},model.id).find(c=>c.artifact.id===artifact.id);if(!selected){show('<section class="card mine-empty"><h1 tabindex="-1" data-run-heading>This version needs another look.</h1><p>The current device checks do not support this run plan.</p><a class="button primary" href="/optimize/'+esc(model.id)+'">Find a version for my computer</a></section>');return;}
 const guide=runInstructions(artifact,config,context);
 show(`<a class="back-link" href="/for-your-device">← Recommendations</a><div class="mine-heading"><div class="eyebrow">RUN IT LOCALLY</div><h1 tabindex="-1" data-run-heading>${esc(model.name)}.<br/>On your computer.</h1><p>${esc(config.chip.name)} · ${config.chip.memory_kind==='discrete'?config.vram_gib:config.ram_gib} GB</p></div><div class="mine-layout"><section class="card mine-detail"><span class="mine-status">Within your memory budget</span><h2>Three steps to your first conversation.</h2><ol class="local-run-steps"><li><span>01</span><div><h3>Set up your computer once</h3><p>Install <a href="https://www.python.org/downloads/" target="_blank" rel="noopener noreferrer">Python 3</a>, the <a href="https://huggingface.co/docs/huggingface_hub/guides/cli" target="_blank" rel="noopener noreferrer">Hugging Face CLI</a>, and <a href="${esc(guide.runtimeURL)}" target="_blank" rel="noopener noreferrer">${esc(guide.runtime)}</a>.</p></div></li><li><span>02</span><div><h3>Download your launcher</h3><p>One small file with the right model version and your computer’s settings.</p><button class="button primary" data-local-run="download">Download launcher ↓</button></div></li><li><span>03</span><div><h3>Start a conversation</h3><p>Open Terminal in the folder where you saved the file and run:</p><pre><code>python3 run-macfit.py</code></pre><p>The first launch downloads ${gb(artifact.actual_size_bytes)} of model files. Type your question when the model is ready.</p></div></li></ol><div id="local-run-notice" role="status"></div><details class="mine-advanced"><summary>Manual setup and advanced information</summary><p>Version: ${esc(artifact.quantization)} · ${esc(artifact.runtime_family)}. Context: ${context.toLocaleString()} tokens.</p><p>Download command</p><pre><code>${esc(guide.download)}</code></pre><p>Manual launch</p><pre><code>${esc(guide.launch)}</code></pre><p>${esc(guide.notes)}</p><p>File revision: ${esc(artifact.revision)}</p><a href="https://huggingface.co/${esc(model.hf_id)}" target="_blank" rel="noopener noreferrer">Publisher model and license ↗</a></details></section><aside class="card mine-selection"><span class="eyebrow">YOUR STARTING POINT</span><h2>${gb(artifact.actual_size_bytes)}</h2><p>Model files · ${gb(selected.row.estimated_required_bytes)} memory plan</p><p>Memory is estimated. Try a short conversation first to check how it performs.</p><div class="mine-section-title"><h3>Make it work your way.</h3></div><p>Add your preferences and examples, then keep it in My models.</p><a class="button secondary full mine-submit" href="/customize/${esc(model.id)}?artifact=${esc(artifact.id)}&context=${context}">Make it mine ✦</a></aside></div>`);
 }catch(e){if(alive&&!controller.signal.aborted)show('<section class="card mine-empty"><h1 tabindex="-1" data-run-heading>Could not prepare your run guide.</h1><p>'+esc(e.message)+'</p><a class="button primary" href="/for-your-device">Back to recommendations</a></section>');}})();
 const onClick=e=>{if(!e.target.closest('[data-local-run]')||!selected)return;try{const item={name:model.name,revision:artifact.revision,context,systemPrompt:'You are a helpful assistant.',examples:[]};const text=runner(runtimeSpec(item,artifact,config));const url=URL.createObjectURL(new Blob([text],{type:'text/x-python'}));const a=document.createElement('a');a.href=url;a.download='run-macfit.py';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);root.querySelector('#local-run-notice').textContent='Launcher prepared. Open the downloaded file from Terminal to begin.';}catch(e){root.querySelector('#local-run-notice').textContent=e.message;}};
 root.addEventListener('click',onClick);
 return ()=>{alive=false;controller.abort();root.removeEventListener('click',onClick);};
}
